language: node_js
node_js:
  - '10'
script:
  - npm run build -- --baseHref=/ng-kanban/ --prod
deploy:
  provider: pages
  local-dir: dist/ng-kanban
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
