import { Injectable } from '@angular/core';
import { select, Store } from '@ngrx/store';
import { Observable, of } from 'rxjs';
import { getCard, State } from '../reducers';
import { AddCard, LoadCards } from './actions';
import { Card } from './card.model';

const CARDS: Card[] = [
  { id: 1, title: 'Learn Angular' },
  { id: 2, title: 'Buy milk' },
  { id: 3, title: 'Server Side Rendering' },
];

// TODO this will be generated by the API
let nextId = 4;

@Injectable()
export class CardService {
  constructor(private store: Store<State>) {}

  load() {
    this.store.dispatch(new LoadCards(CARDS));
  }

  getCard(id: number): Observable<Card> {
    return this.store.pipe(select(getCard, id));
  }

  add(title: string): Observable<Card> {
    const newCard: Card = {
      id: nextId++,
      title,
    };
    this.store.dispatch(new AddCard(newCard));
    return of(newCard);
  }
}
