import { Injectable } from '@angular/core';
import { select, Store } from '@ngrx/store';
import { Observable, of } from 'rxjs';
import { getColumns, State } from '../reducers';
import { AddColumn, InsertCard, LoadColumns, RemoveCard } from './actions';
import { Column } from './column.model';

const COLUMNS: Column[] = [
  {
    id: 1,
    title: 'Backlog',
    cards: [1, 2],
  },
  {
    id: 2,
    title: 'In progress',
    cards: [3],
  },
  {
    id: 3,
    title: 'Done',
    cards: [],
  },
];

// TODO this will be generated by the API
let nextId = 4;

@Injectable()
export class ColumnService {
  constructor(private store: Store<State>) {}

  getColumns(): Observable<Column[]> {
    return this.store.pipe(select(getColumns));
  }

  load() {
    this.store.dispatch(new LoadColumns(COLUMNS));
  }

  moveCard(
    fromColumnId: number,
    toColumnId: number,
    cardId: number,
    position: number,
  ) {
    this.store.dispatch(new RemoveCard({ columnId: fromColumnId, cardId }));
    this.store.dispatch(
      new InsertCard({ columnId: toColumnId, cardId, position }),
    );
  }

  add(title: string): Observable<Column> {
    const newColumn = {
      id: nextId++,
      title,
      cards: [],
    };
    this.store.dispatch(new AddColumn(newColumn));
    return of(newColumn);
  }

  addCardToColumn(cardId: number, columnId: number) {
    this.store.dispatch(new InsertCard({ columnId, cardId }));
  }
}
